package com.example.tianjun.projecttest.SQLite.Custom_serviceInfo;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "CUSTOM_SERVICE_INFO".
 */
@Entity(schema = "custom_serviceInfo")
public class Custom_serviceInfo {

    @Id(autoincrement = true)
    private Long id;
    private String msg_id;
    private String msg_content;
    private String msg_time;
    private String user_name;
    private String avatar;

    @Generated
    public Custom_serviceInfo() {
    }

    public Custom_serviceInfo(Long id) {
        this.id = id;
    }

    @Generated
    public Custom_serviceInfo(Long id, String msg_id, String msg_content, String msg_time, String user_name, String avatar) {
        this.id = id;
        this.msg_id = msg_id;
        this.msg_content = msg_content;
        this.msg_time = msg_time;
        this.user_name = user_name;
        this.avatar = avatar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMsg_id() {
        return msg_id;
    }

    public void setMsg_id(String msg_id) {
        this.msg_id = msg_id;
    }

    public String getMsg_content() {
        return msg_content;
    }

    public void setMsg_content(String msg_content) {
        this.msg_content = msg_content;
    }

    public String getMsg_time() {
        return msg_time;
    }

    public void setMsg_time(String msg_time) {
        this.msg_time = msg_time;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

}
