package com.example.tianjun.projecttest.SQLite.Custom_serviceInfo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.tianjun.projecttest.SQLite.Custom_serviceInfo.Custom_serviceInfo;

import com.example.tianjun.projecttest.SQLite.Custom_serviceInfo.Custom_serviceInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class Custom_serviceInfoDaoSession extends AbstractDaoSession {

    private final DaoConfig custom_serviceInfoDaoConfig;

    private final Custom_serviceInfoDao custom_serviceInfoDao;

    public Custom_serviceInfoDaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        custom_serviceInfoDaoConfig = daoConfigMap.get(Custom_serviceInfoDao.class).clone();
        custom_serviceInfoDaoConfig.initIdentityScope(type);

        custom_serviceInfoDao = new Custom_serviceInfoDao(custom_serviceInfoDaoConfig, this);

        registerDao(Custom_serviceInfo.class, custom_serviceInfoDao);
    }
    
    public void clear() {
        custom_serviceInfoDaoConfig.clearIdentityScope();
    }

    public Custom_serviceInfoDao getCustom_serviceInfoDao() {
        return custom_serviceInfoDao;
    }

}
