package com.example.tianjun.projecttest.SQLite.Baskbar;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.tianjun.projecttest.SQLite.Baskbar.Baskbar;

import com.example.tianjun.projecttest.SQLite.Baskbar.BaskbarDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class BaskbarDaoSession extends AbstractDaoSession {

    private final DaoConfig baskbarDaoConfig;

    private final BaskbarDao baskbarDao;

    public BaskbarDaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        baskbarDaoConfig = daoConfigMap.get(BaskbarDao.class).clone();
        baskbarDaoConfig.initIdentityScope(type);

        baskbarDao = new BaskbarDao(baskbarDaoConfig, this);

        registerDao(Baskbar.class, baskbarDao);
    }
    
    public void clear() {
        baskbarDaoConfig.clearIdentityScope();
    }

    public BaskbarDao getBaskbarDao() {
        return baskbarDao;
    }

}
