package com.example.tianjun.projecttest.SQLite.Baskbar;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BASKBAR".
*/
public class BaskbarDao extends AbstractDao<Baskbar, Long> {

    public static final String TABLENAME = "BASKBAR";

    /**
     * Properties of entity Baskbar.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Share_id = new Property(1, String.class, "share_id", false, "SHARE_ID");
        public final static Property Images = new Property(2, String.class, "images", false, "IMAGES");
        public final static Property Content = new Property(3, String.class, "content", false, "CONTENT");
        public final static Property Nick_name = new Property(4, String.class, "nick_name", false, "NICK_NAME");
    }


    public BaskbarDao(DaoConfig config) {
        super(config);
    }
    
    public BaskbarDao(DaoConfig config, BaskbarDaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BASKBAR\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"SHARE_ID\" TEXT," + // 1: share_id
                "\"IMAGES\" TEXT," + // 2: images
                "\"CONTENT\" TEXT," + // 3: content
                "\"NICK_NAME\" TEXT);"); // 4: nick_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BASKBAR\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Baskbar entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String share_id = entity.getShare_id();
        if (share_id != null) {
            stmt.bindString(2, share_id);
        }
 
        String images = entity.getImages();
        if (images != null) {
            stmt.bindString(3, images);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(4, content);
        }
 
        String nick_name = entity.getNick_name();
        if (nick_name != null) {
            stmt.bindString(5, nick_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Baskbar entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String share_id = entity.getShare_id();
        if (share_id != null) {
            stmt.bindString(2, share_id);
        }
 
        String images = entity.getImages();
        if (images != null) {
            stmt.bindString(3, images);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(4, content);
        }
 
        String nick_name = entity.getNick_name();
        if (nick_name != null) {
            stmt.bindString(5, nick_name);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Baskbar readEntity(Cursor cursor, int offset) {
        Baskbar entity = new Baskbar( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // share_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // images
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // content
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // nick_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Baskbar entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setShare_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setImages(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setContent(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setNick_name(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Baskbar entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Baskbar entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Baskbar entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
