package com.example.tianjun.projecttest.SQLite.Choiceness;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHOICENESS".
*/
public class ChoicenessDao extends AbstractDao<Choiceness, Long> {

    public static final String TABLENAME = "CHOICENESS";

    /**
     * Properties of entity Choiceness.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Topic_id = new Property(1, String.class, "topic_id", false, "TOPIC_ID");
        public final static Property Topic_img = new Property(2, String.class, "topic_img", false, "TOPIC_IMG");
        public final static Property Title = new Property(3, String.class, "title", false, "TITLE");
    }


    public ChoicenessDao(DaoConfig config) {
        super(config);
    }
    
    public ChoicenessDao(DaoConfig config, ChoicenessDaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHOICENESS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TOPIC_ID\" TEXT," + // 1: topic_id
                "\"TOPIC_IMG\" TEXT," + // 2: topic_img
                "\"TITLE\" TEXT);"); // 3: title
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHOICENESS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Choiceness entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String topic_id = entity.getTopic_id();
        if (topic_id != null) {
            stmt.bindString(2, topic_id);
        }
 
        String topic_img = entity.getTopic_img();
        if (topic_img != null) {
            stmt.bindString(3, topic_img);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Choiceness entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String topic_id = entity.getTopic_id();
        if (topic_id != null) {
            stmt.bindString(2, topic_id);
        }
 
        String topic_img = entity.getTopic_img();
        if (topic_img != null) {
            stmt.bindString(3, topic_img);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(4, title);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Choiceness readEntity(Cursor cursor, int offset) {
        Choiceness entity = new Choiceness( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // topic_id
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // topic_img
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // title
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Choiceness entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTopic_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTopic_img(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTitle(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Choiceness entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Choiceness entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Choiceness entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
