package com.example.tianjun.projecttest.SQLite.Choiceness;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.tianjun.projecttest.SQLite.Choiceness.Choiceness;

import com.example.tianjun.projecttest.SQLite.Choiceness.ChoicenessDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class ChoicenessDaoSession extends AbstractDaoSession {

    private final DaoConfig choicenessDaoConfig;

    private final ChoicenessDao choicenessDao;

    public ChoicenessDaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        choicenessDaoConfig = daoConfigMap.get(ChoicenessDao.class).clone();
        choicenessDaoConfig.initIdentityScope(type);

        choicenessDao = new ChoicenessDao(choicenessDaoConfig, this);

        registerDao(Choiceness.class, choicenessDao);
    }
    
    public void clear() {
        choicenessDaoConfig.clearIdentityScope();
    }

    public ChoicenessDao getChoicenessDao() {
        return choicenessDao;
    }

}
