package com.example.tianjun.projecttest.SQLite.Choiceness;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "CHOICENESS".
 */
@Entity(schema = "choiceness")
public class Choiceness {

    @Id(autoincrement = true)
    private Long id;
    private String topic_id;
    private String topic_img;
    private String title;

    @Generated
    public Choiceness() {
    }

    public Choiceness(Long id) {
        this.id = id;
    }

    @Generated
    public Choiceness(Long id, String topic_id, String topic_img, String title) {
        this.id = id;
        this.topic_id = topic_id;
        this.topic_img = topic_img;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTopic_id() {
        return topic_id;
    }

    public void setTopic_id(String topic_id) {
        this.topic_id = topic_id;
    }

    public String getTopic_img() {
        return topic_img;
    }

    public void setTopic_img(String topic_img) {
        this.topic_img = topic_img;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
