package com.example.tianjun.projecttest.SQLite.AddressInfo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.tianjun.projecttest.SQLite.AddressInfo.AddressInfo;

import com.example.tianjun.projecttest.SQLite.AddressInfo.AddressInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class AddressInfoDaoSession extends AbstractDaoSession {

    private final DaoConfig addressInfoDaoConfig;

    private final AddressInfoDao addressInfoDao;

    public AddressInfoDaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressInfoDaoConfig = daoConfigMap.get(AddressInfoDao.class).clone();
        addressInfoDaoConfig.initIdentityScope(type);

        addressInfoDao = new AddressInfoDao(addressInfoDaoConfig, this);

        registerDao(AddressInfo.class, addressInfoDao);
    }
    
    public void clear() {
        addressInfoDaoConfig.clearIdentityScope();
    }

    public AddressInfoDao getAddressInfoDao() {
        return addressInfoDao;
    }

}
