package com.example.tianjun.projecttest.SQLite.AddressInfo;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "ADDRESS_INFO".
 */
@Entity(schema = "addressInfo")
public class AddressInfo {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String userNamne;

    @NotNull
    private String cityInfo;

    @NotNull
    private String address;

    @NotNull
    private String phoneNum;
    private String locPhoneNum;

    @NotNull
    private String postalcode;
    private Boolean defaults;

    @Generated
    public AddressInfo() {
    }

    public AddressInfo(Long id) {
        this.id = id;
    }

    @Generated
    public AddressInfo(Long id, String userNamne, String cityInfo, String address, String phoneNum, String locPhoneNum, String postalcode, Boolean defaults) {
        this.id = id;
        this.userNamne = userNamne;
        this.cityInfo = cityInfo;
        this.address = address;
        this.phoneNum = phoneNum;
        this.locPhoneNum = locPhoneNum;
        this.postalcode = postalcode;
        this.defaults = defaults;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getUserNamne() {
        return userNamne;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserNamne(@NotNull String userNamne) {
        this.userNamne = userNamne;
    }

    @NotNull
    public String getCityInfo() {
        return cityInfo;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCityInfo(@NotNull String cityInfo) {
        this.cityInfo = cityInfo;
    }

    @NotNull
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(@NotNull String address) {
        this.address = address;
    }

    @NotNull
    public String getPhoneNum() {
        return phoneNum;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhoneNum(@NotNull String phoneNum) {
        this.phoneNum = phoneNum;
    }

    public String getLocPhoneNum() {
        return locPhoneNum;
    }

    public void setLocPhoneNum(String locPhoneNum) {
        this.locPhoneNum = locPhoneNum;
    }

    @NotNull
    public String getPostalcode() {
        return postalcode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPostalcode(@NotNull String postalcode) {
        this.postalcode = postalcode;
    }

    public Boolean getDefault() {
        return defaults;
    }

    public void setDefault(Boolean defaults) {
        this.defaults = defaults;
    }

}
