package com.example.tianjun.projecttest.SQLite.UserInfo;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "USER_INFO".
 */
@Entity(schema = "userInfo")
public class UserInfo {

    @Id(autoincrement = true)
    private Long id;
    private String userName;
    private String sex;
    private String birthday;
    private String phoneNum;
    private String email;

    @Generated
    public UserInfo() {
    }

    public UserInfo(Long id) {
        this.id = id;
    }

    @Generated
    public UserInfo(Long id, String userName, String sex, String birthday, String phoneNum, String email) {
        this.id = id;
        this.userName = userName;
        this.sex = sex;
        this.birthday = birthday;
        this.phoneNum = phoneNum;
        this.email = email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getPhoneNum() {
        return phoneNum;
    }

    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
