package com.example.tianjun.projecttest.SQLite.ShoppingCar;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "SHOPPING_CAR".
 */
@Entity(schema = "shoppingcar")
public class ShoppingCar {

    @Id(autoincrement = true)
    private Long id;
    private String goods_id;
    private String goods_english_name;
    private String goods_name;
    private String shop_price;
    private Integer num;

    @Generated
    public ShoppingCar() {
    }

    public ShoppingCar(Long id) {
        this.id = id;
    }

    @Generated
    public ShoppingCar(Long id, String goods_id, String goods_english_name, String goods_name, String shop_price, Integer num) {
        this.id = id;
        this.goods_id = goods_id;
        this.goods_english_name = goods_english_name;
        this.goods_name = goods_name;
        this.shop_price = shop_price;
        this.num = num;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGoods_id() {
        return goods_id;
    }

    public void setGoods_id(String goods_id) {
        this.goods_id = goods_id;
    }

    public String getGoods_english_name() {
        return goods_english_name;
    }

    public void setGoods_english_name(String goods_english_name) {
        this.goods_english_name = goods_english_name;
    }

    public String getGoods_name() {
        return goods_name;
    }

    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name;
    }

    public String getShop_price() {
        return shop_price;
    }

    public void setShop_price(String shop_price) {
        this.shop_price = shop_price;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

}
