package com.example.tianjun.projecttest.SQLite.ShoppingCar;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.tianjun.projecttest.SQLite.ShoppingCar.ShoppingCar;

import com.example.tianjun.projecttest.SQLite.ShoppingCar.ShoppingCarDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class ShoppingcarDaoSession extends AbstractDaoSession {

    private final DaoConfig shoppingCarDaoConfig;

    private final ShoppingCarDao shoppingCarDao;

    public ShoppingcarDaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shoppingCarDaoConfig = daoConfigMap.get(ShoppingCarDao.class).clone();
        shoppingCarDaoConfig.initIdentityScope(type);

        shoppingCarDao = new ShoppingCarDao(shoppingCarDaoConfig, this);

        registerDao(ShoppingCar.class, shoppingCarDao);
    }
    
    public void clear() {
        shoppingCarDaoConfig.clearIdentityScope();
    }

    public ShoppingCarDao getShoppingCarDao() {
        return shoppingCarDao;
    }

}
